site_name: Acquire Docs
repo_url: https://github.com/acquire-project

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - content.code.copy
  custom_dir: overrides

extra_css:
  - stylesheets/custom.css

nav:
  - Home: index.md
  - Get Started: get_started.md
  - API Reference: api_reference.md
  - Tutorials:
    - tutorials/tutorials.md
    - tutorials/trigger.md
    - tutorials/configure.md
    - tutorials/framedata.md
    - tutorials/start_stop.md
    - tutorials/livestream.md
    - tutorials/select.md
    - tutorials/setup.md
    - tutorials/props_json.md
    - tutorials/trig_json.md
    - tutorials/multiscale.md
    - tutorials/chunked.md
    - tutorials/drivers.md
    - tutorials/storage.md
  - For contributors: 
    - for_contributors/for_contributors.md
    - for_contributors/docs_contribution_quickstart.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      options:
        custom_icons:
          - overrides/.icons

plugins:
  - include-markdown
  - search
