site_name: Acquire Docs
repo_url: https://github.com/acquire-project/
site_url: https://acquire-project.github.io/acquire-docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    - content.code.copy
    - toc.follow
  custom_dir: overrides
  palette:
    # Palette toggle shown in light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle shown in dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

extra_css:
  - stylesheets/custom.css

extra_javascript:
  - javascripts/version-select.js

nav:
  - Home: index.md
  - Get Started: get_started.md
  - API Reference: api_reference.md
  - Tutorials:
    - tutorials/index.md
    - tutorials/trigger.md
    - tutorials/configure.md
    - tutorials/framedata.md
    - tutorials/start_stop.md
    - tutorials/livestream.md
    - tutorials/select.md
    - tutorials/setup.md
    - tutorials/props_json.md
    - tutorials/trig_json.md
    - tutorials/multiscale.md
    - tutorials/chunked.md
    - tutorials/drivers.md
    - tutorials/storage.md
    - tutorials/compressed.md
  - For contributors:
    - for_contributors/index.md
    - for_contributors/docs_contribution_quickstart.md
    - for_contributors/update_version.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      options:
        custom_icons:
          - overrides/.icons
  - toc:
      permalink: true
  - attr_list
  - pymdownx.magiclink


plugins:
  - include-markdown
  - search
  - mkdocstrings:
      custom_templates: docs/_templates
      handlers:
        python:
          # Global-only options
          load_external_modules: true
          paths: [../acquire-python/python/acquire]
          import:
            - https://docs.python.org/3/objects.inv
          options:  # See https://mkdocstrings.github.io/python/usage/#globallocal-options
            # General options
            enable_inventory: true  # Create an objects.inv file
            show_source: false  # Do now show source code for objects
            # Heading options
            show_root_heading: false  # Do now show module name as heading, default
            show_root_toc_entry: false  # Do not create anchor for acquire module itself
            show_root_members_full_path: true  # Show full path for members, i.e.
                                               # acquire.Camera instead of Camera
            show_symbol_type_heading: true  # Show the symbol type in headings (i.e. `method`, `class`)
            # Members options
            members: true  # An explicit list of members to render (true for all)
            inherited_members: false  # Do not render any inherited members (for classes)
            members_order: "alphabetical"  # Order members alphabetically, default
            filters: ["!^_", "!dict"]  # Remove private and unwanted members
            summary: true  # Whether to render summaries of objects. Insiders only for now
            show_labels: false  # Whether to show labels of the members
            # Docstring options
            docstring_style: google
            # docstring_options: {}  # Can be customized, see https://mkdocstrings.github.io/python/usage/configuration/docstrings/#docstring_options
            docstring_section_style: table  # The style used to render docstring sections, default
            show_if_no_docstring: false  # Default
            # Signature/annotation options
            annotations_path: "brief"  # The verbosity for annotations path, default
            show_signature_annotations: true  # Show the type annotations in methods and functions signatures
            signature_crossrefs: true  # Whether to render cross-references for type annotations in signatures
