site_name: Acquire Docs
repo_url: https://github.com/acquire-project/
site_url: https://acquire-project.github.io/acquire-docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    - content.code.copy
    - toc.follow
  custom_dir: overrides
  palette:
    # Palette toggle shown in light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle shown in dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

extra_css:
  - stylesheets/custom.css

extra_javascript:
  - javascripts/version-select.js

nav:
  - Home: index.md
  - Get Started: get_started.md
  - API Reference: api_reference.md
  - Tutorials:
    - tutorials/index.md
    - Setup acquisition:
      - tutorials/setup_acquisition/index.md
      - tutorials/setup_acquisition/trigger.md
      - tutorials/setup_acquisition/configure.md
      - tutorials/setup_acquisition/start_stop.md
      - tutorials/setup_acquisition/select.md
      - tutorials/setup_acquisition/setup.md
      - tutorials/setup_acquisition/drivers.md
      - tutorials/setup_acquisition/storage.md
    - Using JSON:
      - tutorials/using_json/index.md
      - tutorials/using_json/trig_json.md
      - tutorials/using_json/props_json.md
    - Data:
      - tutorials/access_data/index.md
      - tutorials/access_data/framedata.md
      - tutorials/access_data/livestream.md
    - Zarr:
      - tutorials/zarr/index.md
      - tutorials/zarr/multiscale.md
      - tutorials/zarr/chunked.md
      - tutorials/zarr/compressed.md
  - For contributors:
    - for_contributors/index.md
    - for_contributors/docs_contribution_quickstart.md
    - for_contributors/update_version.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      options:
        custom_icons:
          - overrides/.icons
  - toc:
      permalink: true
  - attr_list
  - pymdownx.magiclink


plugins:
  - include-markdown
  - search
  - mkdocstrings:
      custom_templates: docs/_templates
      handlers:
        python:
          # Global-only options
          load_external_modules: true
          paths: [../acquire-python/python/acquire]
          import:
            - https://docs.python.org/3/objects.inv
          options:  # See https://mkdocstrings.github.io/python/usage/#globallocal-options
            # General options
            find_stubs_package: true
            allow_inspection: true
            show_bases: true
            show_source: false
            preload_modules: ""
            # Heading options
            heading_level: 2
            parameter_headings: true
            show_root_heading: false
            annotations_path: source
            enable_inventory: true
            show_root_toc_entry: false
            show_root_full_path: true
            show_root_members_full_path: true
            show_object_full_path: false
            show_category_heading: false
            show_symbol_type_heading: true
            show_symbol_type_toc: false
            # Members options
            inherited_members: false
            members: true
            members_order: "alphabetical"
            filters: ["!^_", "!dict"]  # Remove private members
            group_by_category: true
            show_submodules: false
            summary: true
            show_labels: false
            # Docstring options
            docstring_style: google
            # docstring_options: {}
            docstring_section_style: table
            merge_init_into_class: false
            show_if_no_docstring: false
            # Signature/annotation options
            annotations_path: "brief"
            line_length: 60
            show_signature: true
            show_signature_annotations: true
            signature_crossrefs: true
            separate_signature: false
            unwrap_annotated: false
            modernize_annotations: false
